/*
File:         discrete_fourier_transform.h
Purpose:      Contains prototypes for a fast discrete Fourier
transformation based on code available at:
http://paulbourke.net/miscellaneous/dft/
Author:		   Xinyi Zhao and Bailey Doering
Student #s:		90762543 nd 12345678
CS Accounts:	xxinyiz@students.cs.ubc.ca and b2b2
Date:		    September 11, 2024
*/

/********************************************************************
DO NOT EDIT THIS FILE
******************************************************************/

#pragma once

/* Function prototype */
void fft(short int dir, long m, double x[], double y[]);